### PR TITLE
Changed some styling of the webpage

### PR DESCRIPTION
**Pull request by nabeelahmedjh**
I added some custom css and changed a little bit of index.html in order to sync with the webpage. My aim was to improve the look of the website which I think I have achieved. my branch is deployed here: https://nabeelahmedjh.github.io/MLSA/

### CODE REVIEW

**Comment by XFarooqi** [comment]
Hello Nabeel,

I really appreciate the hard work and changes that you have made. But unfortunately, I can not merge them as the font family and some other stuff are instructed by our partners. Don't worry, we utilize these changes on GDSC Website.

Moreover, these changes made some components out of shape as you can see in the blogs section, and also the branch has conflicts with the main branch.

Meanwhile, I will really love it if you can PR the 50% ratio of the team images only.

**Comment by nabeelahmedjh** [comment]
removed some of the conflicts and reviewed changes except the blog post section everything is same so I create this branch for you to review

**Review by XFarooqi — CHANGES_REQUESTED** [review]
can you plz PR the ratio of the image?

**Comment by nabeelahmedjh** [comment]
Sure

**Pull request closed without merging**
